const foodList = [
    {
        "ID": "1",
        "FILE NAME": "Aloo butter paratha.jpg",
        "NAME": "Aloo butter paratha",
        "Food Type": "Roti",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "2",
        "FILE NAME": "Bacon salad.jpg",
        "NAME": "Bacon salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "3",
        "FILE NAME": "Blackbeery cocktail.jpg",
        "NAME": "Blackbeery cocktail",
        "Food Type": "Drinks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "4",
        "FILE NAME": "Blue Shot.jpg",
        "NAME": "Blue Shot",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "5",
        "FILE NAME": "Bread Pakore.jpg",
        "NAME": "Bread Pakore",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "6",
        "FILE NAME": "Broccali Salad.jpg",
        "NAME": "Broccali Salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "7",
        "FILE NAME": "Butter Chicken.jpg",
        "NAME": "Butter Chicken",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "8",
        "FILE NAME": "Butter Mutton.jpg",
        "NAME": "Butter Mutton",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "9",
        "FILE NAME": "Butter Naan.jpg",
        "NAME": "Butter Naan",
        "Food Type": "Roti",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "10",
        "FILE NAME": "Butter Parathe.jpg",
        "NAME": "Butter Parathe",
        "Food Type": "Roti",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "11",
        "FILE NAME": "Butter Roti.jpg",
        "NAME": "Butter Roti",
        "Food Type": "Roti",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "12",
        "FILE NAME": "Caspere Salad.jpg",
        "NAME": "Caspere Salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "13",
        "FILE NAME": "Chicken Biryani.jpg",
        "NAME": "Chicken Biryani",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "14",
        "FILE NAME": "Chicken Curry.jpg",
        "NAME": "Chicken Curry",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "15",
        "FILE NAME": "Chicken King.jpg",
        "NAME": "Chicken King",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "16",
        "FILE NAME": "Chicken Lollipop.jpg",
        "NAME": "Chicken Lollipop",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "17",
        "FILE NAME": "Chicken Momo.jpg",
        "NAME": "Chicken Momo",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "18",
        "FILE NAME": "Chicken Noodles.jpg",
        "NAME": "Chicken Noodles",
        "Food Type": "Meal",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "19",
        "FILE NAME": "Chicken Pakore.jpg",
        "NAME": "Chicken Pakore",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "20",
        "FILE NAME": "Chilled Orange Juice.jpg",
        "NAME": "Chilled Orange Juice",
        "Food Type": "Drinks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "21",
        "FILE NAME": "Choclate Shake.jpg",
        "NAME": "Choclate Shake",
        "Food Type": "Drinks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "22",
        "FILE NAME": "Classic Ramen.jpg",
        "NAME": "Classic Ramen",
        "Food Type": "Meal",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "23",
        "FILE NAME": "Egg Salad.jpg",
        "NAME": "Egg Salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "24",
        "FILE NAME": "Fruit Green Salad.jpg",
        "NAME": "Fruit Green Salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "25",
        "FILE NAME": "Fruit Salad.jpg",
        "NAME": "Fruit Salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "26",
        "FILE NAME": "Fry Momo.jpg",
        "NAME": "Fry Momo",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "27",
        "FILE NAME": "Fry Rice.jpg",
        "NAME": "Fry Rice",
        "Food Type": "Rice",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "28",
        "FILE NAME": "Green Pakore Shots.jpg",
        "NAME": "Green Pakore Shots",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "29",
        "FILE NAME": "Green Pakore.jpg",
        "NAME": "Green Pakore",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "30",
        "FILE NAME": "Grilled Chicken.jpg",
        "NAME": "Grilled Chicken",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "31",
        "FILE NAME": "Grilled meat.jpg",
        "NAME": "Grilled meat",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "32",
        "FILE NAME": "Jira Rice.jpg",
        "NAME": "Jira Rice",
        "Food Type": "Rice",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "33",
        "FILE NAME": "Large Breakfast.jpg",
        "NAME": "Large Breakfast",
        "Food Type": "Meal",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "34",
        "FILE NAME": "Naruto Ramen.jpg",
        "NAME": "Naruto Ramen",
        "Food Type": "Meal",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "35",
        "FILE NAME": "Meat Fry.jpg",
        "NAME": "Meat Fry",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "36",
        "FILE NAME": "Mix Fruit Shake.jpg",
        "NAME": "Mix Fruit Shake",
        "Food Type": "Drinks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "37",
        "FILE NAME": "Mix Lemon Cocktail.jpg",
        "NAME": "Mix Lemon Cocktail",
        "Food Type": "Drinks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "38",
        "FILE NAME": "Momo.jpg",
        "NAME": "Momo",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "39",
        "FILE NAME": "Momos with spicy sauce dip.jpg",
        "NAME": "Momos with spicy sauce dip",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "40",
        "FILE NAME": "Mung Daal ke pakore.jpg",
        "NAME": "Mung Daal ke pakore",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "41",
        "FILE NAME": "Mutton Biryani.jpg",
        "NAME": "Mutton Biryani",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "42",
        "FILE NAME": "Mutton Chilli Fry.jpg",
        "NAME": "Mutton Chilli Fry",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "43",
        "FILE NAME": "Mutton Curry.jpg",
        "NAME": "Mutton Curry",
        "Food Type": "Non-Veg",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "44",
        "FILE NAME": "Naan Roti.jpg",
        "NAME": "Naan Roti",
        "Food Type": "Roti",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "45",
        "FILE NAME": "Naan.jpg",
        "NAME": "Naan",
        "Food Type": "Roti",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "46",
        "FILE NAME": "Nebula Ice Shot.jpg",
        "NAME": "Nebula Ice Shot",
        "Food Type": "Drinks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "47",
        "FILE NAME": "Orange Juice.jpg",
        "NAME": "Orange Juice",
        "Food Type": "Drinks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "48",
        "FILE NAME": "Paneer Masala.jpg",
        "NAME": "Paneer Masala",
        "Food Type": "Paneer",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "49",
        "FILE NAME": "Paneer Pakore.jpg",
        "NAME": "Paneer Pakore",
        "Food Type": "Paneer",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "50",
        "FILE NAME": "Paneer Tikka.jpg",
        "NAME": "Paneer Tikka",
        "Food Type": "Paneer",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "51",
        "FILE NAME": "Pasta Salad.jpg",
        "NAME": "Pasta Salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "52",
        "FILE NAME": "Pawn Noodles.jpg",
        "NAME": "Pawn Noodles",
        "Food Type": "Meal",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "53",
        "FILE NAME": "Potato Salad.jpg",
        "NAME": "Potato Salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "54",
        "FILE NAME": "Potato Veggie Salad.jpg",
        "NAME": "Potato Veggie Salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "55",
        "FILE NAME": "Pulao.jpg",
        "NAME": "Pulao",
        "Food Type": "Rice",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "56",
        "FILE NAME": "Pyaj ke pakore.jpg",
        "NAME": "Pyaj ke pakore",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "57",
        "FILE NAME": "pyaz pakore.jpg",
        "NAME": "pyaz pakore",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "58",
        "FILE NAME": "Pyaz Parathe.jpg",
        "NAME": "Pyaz Parathe",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "59",
        "FILE NAME": "Rainbow Salad.jpg",
        "NAME": "Rainbow Salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "60",
        "FILE NAME": "Red Berry Cocktail.jpg",
        "NAME": "Red Berry Cocktail",
        "Food Type": "Drinks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "61",
        "FILE NAME": "Red Orange Shake.jpg",
        "NAME": "Red Orange Shake",
        "Food Type": "Drinks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "62",
        "FILE NAME": "Sahi Paneer.jpg",
        "NAME": "Sahi Paneer",
        "Food Type": "Paneer",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "63",
        "FILE NAME": "Speggati.jpg",
        "NAME": "Speggati",
        "Food Type": "Meal",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "64",
        "FILE NAME": "Spicy Momos.jpg",
        "NAME": "Spicy Momos",
        "Food Type": "Snacks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "65",
        "FILE NAME": "Sprout Salad Bowl.jpg",
        "NAME": "Sprout Salad Bowl",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "66",
        "FILE NAME": "Sprout Salad.jpg",
        "NAME": "Sprout Salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "67",
        "FILE NAME": "Strawberry Jar.jpg",
        "NAME": "Strawberry Jar",
        "Food Type": "Drinks",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "68",
        "FILE NAME": "Tomato Cherry Salad.jpg",
        "NAME": "Tomato Cherry Salad",
        "Food Type": "Salad",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "69",
        "FILE NAME": "Veg Birayani.jpg",
        "NAME": "Veg Birayani",
        "Food Type": "Meal",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "70",
        "FILE NAME": "Veg Maggie.jpg",
        "NAME": "Veg Maggie",
        "Food Type": "Meal",
        "QTY":0,
        "isSeleted": false,
    },
    {
        "ID": "71",
        "FILE NAME": "Watermelon Cocktail.jpg",
        "NAME": "Watermelon Cocktail",
        "Food Type": "Drinks",
        "QTY":0,
        "isSeleted": false,
    }
]

export { foodList };